spring:
  mvc:
    format:
      date: "yyyy-MM-dd"
  config:
    import:
      optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate


client:
  epl:
    host: ${EPL_LINK}
    search: /search

settings:
  time-zone: Europe/Moscow

shop:
  trial-subscription-days: ${TRIAL_SUBSCRIPTION_DAYS}

parser:
  epl:
    first-selector-for-image: body > div.l-wrapper > section.l-content.js-content > div > div.search-page.js-data > ul > li > div > a > img
    image-not-found-url: /local/templates/.default/img/no_picture_big.png

    link-product: body > div.l-wrapper > section.l-content.js-content > div > div.search-page.js-data > ul > li > div > div > div > a
    second-selector-for-image: body > div.l-wrapper > section.l-content.js-content > div > div.b-card-page.js-card-page > div.b-card-page__row > div.b-card-page__views > div > div > div.b-card-page__views-container > ul > li:nth-child(1) > a > img

    count: body > div.l-wrapper > section.l-content.js-content > div > div.search-page.js-data > div