spring:
  mvc:
    format:
      date: "yyyy-MM-dd"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jeweler_db
    username: postgres
    password: 12345

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate
